export type ChallengeProject = {
  day: number;
  title: string;
  description?: string;
  url?: string;
  repo?: string;
  completed: boolean;
  pendingStore?: boolean;
};

export const challengeProjects: ChallengeProject[] = [
  {
    day: 1,
    title: "Portfolio Site",
    description: "Personal portfolio built with Next.js 16, Tailwind CSS v4, and MDX.",
    url: "https://reneebe.github.io",
    completed: true,
  },
  {
    day: 2,
    title: "Portfolio Skins",
    description: "Theme switcher for my portfolio — pre-made skins and AI-generated themes from a text description.",
    url: "https://reneebe.github.io/portfolio-skins",
    repo: "https://github.com/reneebe/portfolio-skins",
    completed: true,
  },
  {
    day: 3,
    title: "Nano Claude Theme Manager",
    description: "Cloudflare Worker that chains Gemini image generation + Claude vision to produce ThemeVars JSON from a text description.",
    repo: "https://github.com/ReneeBe/nano-claude-theme-manager",
    completed: true,
  },
  {
    day: 4,
    title: "Theme Generator",
    description: "Vite/React UI for AI theme generation — describe a vibe, get a full UI theme powered by Gemini + Claude.",
    url: "https://reneebe.github.io/theme-generator",
    repo: "https://github.com/ReneeBe/theme-generator",
    completed: true,
  },
  {
    day: 5,
    title: "Theme Extension",
    description: "Chrome extension that injects AI-generated CSS themes into any website with one click.",
    url: "https://chromewebstore.google.com/detail/theme-generator/nmbpjgbbogokabhnmkonpgfeglebeidi",
    repo: "https://github.com/ReneeBe/theme-extension",
    completed: true,
  },
  {
    day: 6,
    title: "Accessibility Auditor",
    description: "Paste a React component and get a list of WCAG 2.2 issues detected via static AST analysis. No backend, no AI — pure client-side.",
    url: "/tools/accessibility-auditor/",
    repo: "https://github.com/reneebe/accessibilityAuditor",
    completed: true,
  },
  {
    day: 7,
    title: "Persist",
    description: "Chrome extension + Cloudflare Worker that captures full page context and lets you selectively share it with AI agents via REST or MCP.",
    url: "https://chromewebstore.google.com/detail/persist/jjcahbgnbbnkflafdbbhimpdfpaibelo",
    repo: "https://github.com/ReneeBe/persist",
    completed: true,
  },
  {
    day: 8,
    title: "Brain Dump Scheduler",
    description: "Paste a free-form brain dump and Claude extracts, prioritizes, and schedules your tasks into a timeline view.",
    url: "https://reneebe.github.io/brain-dump-scheduler",
    repo: "https://github.com/ReneeBe/brain-dump-scheduler",
    completed: true,
  },
  {
    day: 9,
    title: "Type Speed Test",
    description: "A typing speed test with live WPM, accuracy, and error tracking. Dark and light mode included.",
    url: "https://reneebe.github.io/type-speed-test/",
    repo: "https://github.com/ReneeBe/type-speed-test",
    completed: true,
  },
  {
    day: 10,
    title: "Pomodoro Timer",
    description: "Customizable Pomodoro timer with configurable focus and break durations, and separate alarm sound selection for each mode.",
    url: "https://reneebe.github.io/pomodoro-timer/",
    repo: "https://github.com/ReneeBe/pomodoro-timer",
    completed: true,
  },
  {
    day: 11,
    title: "AI Video Searcher",
    description: "Upload a video and search for any moment using plain English. Powered by Gemini.",
    url: "https://reneebe.github.io/ai-video-searcher/",
    repo: "https://github.com/ReneeBe/ai-video-searcher",
    completed: true,
  },
  {
    day: 12,
    title: "Photo Location Quiz",
    description: "Upload your iPhone camera roll and guess where each photo was taken. GPS extraction, reverse geocoding, and AI-generated decoy cities.",
    url: "https://reneebe.github.io/photo-location-quiz/",
    repo: "https://github.com/ReneeBe/photo-location-quiz",
    completed: true,
  },
  {
    day: 13,
    title: "Idea Explorer",
    description: "Spatial concept map powered by Claude. Enter a topic, answer two follow-up questions, and explore ideas as an interactive graph you can keep drilling into.",
    url: "https://reneebe.github.io/idea-explorer/",
    repo: "https://github.com/ReneeBe/idea-explorer",
    completed: true,
  },
  {
    day: 14,
    title: "Project Peek",
    description: "A reusable React component for portfolio project cards — click to peek at the description, demo, repo, and blog post. Published as an npm package.",
    url: "https://reneebe.github.io/project-peek/",
    repo: "https://github.com/ReneeBe/project-peek",
    completed: true,
  },
  {
    day: 15,
    title: "MagicLink",
    description: "A Cloudflare Worker that issues demo tokens to recruiters, letting them try AI-powered portfolio projects up to 5 times without needing their own API keys.",
    url: "https://magiclink.reneebe.workers.dev",
    repo: "https://github.com/ReneeBe/magiclink",
    completed: true,
  },
  {
    day: 16,
    title: "Haiku Generator",
    description: "Describe a feeling, a scene, a moment — and Claude Haiku composes a 5-7-5 haiku. MagicLink demo or bring your own API key.",
    url: "https://reneebe.github.io/haiku/",
    repo: "https://github.com/ReneeBe/haiku",
    completed: true,
  },
  {
    day: 17,
    title: "Haiku Playground",
    description: "An interactive upgrade to the Day 16 haiku generator: real-time generation as you type, syllable highlighting with color-coded positions, and drag-to-rearrange words.",
    url: "https://reneebe.github.io/haiku/",
    repo: "https://github.com/ReneeBe/haiku",
    completed: true,
  },
  {
    day: 18,
    title: "Rosetta",
    description: "Paste code in one language, pick a target translation language, and get a three-column breakdown: original, translated, and a line-by-line explanation of every difference.",
    url: "https://reneebe.github.io/rosetta/",
    repo: "https://github.com/ReneeBe/rosetta",
    completed: true,
  },
  {
    day: 19,
    title: "Neighborhood Compare",
    description: "Pick two neighborhoods and compare them side by side: custom walkability score, amenity counts, median rent, schools, air quality, and draggable map exploration.",
    url: "https://reneebe.github.io/neighborhood-compare/",
    repo: "https://github.com/ReneeBe/neighborhood-compare",
    completed: true,
  },
  {
    day: 20,
    title: "Mobile-Friendly Portfolio",
    description: "Made the entire portfolio responsive — scaled headings, padding, nav, and layouts across all pages for phones and tablets.",
    completed: true,
  },
  {
    day: 21,
    title: "MagicLink 2.0",
    description: "A rebuild of the demo token system: no email gate, per-visitor IP-hashed quotas, /resume one-click links for recruiters, an analytics dashboard, and idempotency for retry-prone projects.",
    url: "https://magiclink.reneebe.workers.dev",
    repo: "https://github.com/ReneeBe/magiclink",
    completed: true,
  },
  {
    day: 22,
    title: "Walking Isochrone Map",
    description: "Drop a pin anywhere on the globe and see how far you can walk in 5, 10, 20, 30, 45, or 60 minutes — concentric color bands powered by the Mapbox Isochrone API and turf.js polygon subtraction.",
    url: "https://reneebe.github.io/isochrone-map/",
    repo: "https://github.com/ReneeBe/isochrone-map",
    completed: true,
  },
  ...Array.from({ length: 28 }, (_, i) => ({
    day: i + 23,
    title: `Day ${i + 23}`,
    completed: false,
  })),
];
